### ISSUE TITLE
适配器泛型指定问题、文档上没有说明

### ISSUE THREAD

**Issue by zhaobinsir** [Shouheng88/xAdapter#2]
![image](https://user-images.githubusercontent.com/28432309/135220069-0822f5c3-45b9-4832-a3c8-aee1eef2628c.png)
![image](https://user-images.githubusercontent.com/28432309/135220117-e23d988d-c8c1-4c35-90a5-03ef6b311280.png)
关注下吧、搞不清楚传什么！

**Comment by Shouheng88** [comment]
列表要展示什么数据就传什么类型啊，如果支持多类型就传公共基类或者接口
