### ISSUE TITLE
BaseQuickAdapter能否升级到3.0以上？

### ISSUE THREAD

**Issue by mxdlsm** [Shouheng88/xAdapter#3]
我想用这个库，但是BaseQuickAdapter您能升级一下么？

**Comment by Shouheng88** [comment]
我后面升级下，你可以用下面的方法排除掉 brvah，然后使用自己的版本
```
implementation("com.github.Shouheng88:xadapter:1.1") {
    exclude(group = "com.github.CymChad", module = "BaseRecyclerViewAdapterHelper")
}
```

**Comment by mxdlsm** [comment]
谢谢，辛苦了。因为3.0以上写法有些不一样

**Comment by Shouheng88** [comment]
BRVAH 的开发向下兼容没做好，我看了下迁移成本太高了，我暂时不准备迁移到 3.x 的。BRVAH 3.x 中增加了一些数据绑定的逻辑，作用并不大。而且 BRVAH 已经多年没有维护，后面如果有问题，我会基于 2.x 版本自己维护。
